version: "3.8"

networks:
  todolist-network:
    driver: bridge

services:
# api
  api:
    networks:
      - todolist-network
    container_name: api
    restart: always
    image: ${DOCKER_HUB_USER}/todolist-skypro:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    links:
      - postgres
    environment:
      DATABASE_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    expose:
      - "8000"
# migrations
  migrations:
    networks:
      - todolist-network
    image: ${DOCKER_HUB_USER}/todolist-skypro:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    links:
      - postgres
    environment:
      DATABASE_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["python", "skypro/manage.py", "migrate", "--noinput"]
# postgres
  postgres:
    networks:
      - todolist-network
    container_name: todolist_pg_db
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - todolist_pgdata:/var/lib/postgresql/data
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready --username=${POSTGRES_USER} --dbname=${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 3
# frontend
  front:
    networks:
      - todolist-network
    container_name: todolist_nginx_front
    image: sermalenk/skypro-front:lesson-34
    depends_on:
      - api
    ports:
      - "8080:80"
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
# pgdata for postgres
  todolist_pgdata:
    driver: local
